name: backend-test
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  backend-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Set up Golang
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Spin up containers
      run: docker compose --env-file example.env up -d
    - name: Running Tests
      run: ENV=example.env make test
